### ISSUE TITLE
Results reproduction text-to-4D

### ISSUE THREAD

**Issue by kate-feingold** [NVlabs/dream-in-4d#1]
Hi! Thank you for sharing the code. I’m trying to reproduce your results and I’m getting a strange result for the animation stage.
I’m running a text-to-3D pipeline followed by 3D-to-4D for a prompt "A panda is riding a bicycle" using the commands specified in the README and modifying the yamls with the prompt accordingly. For the static scene part, I’m getting a nice model very similar to the one in your project page. However, during the animation, the video looks very zoomed in, and the quality of the shapes degrades. Sharing the final videos from both stages and yamls of the 2nd stage.

Could you please check what's missing?

https://github.com/user-attachments/assets/ad7b2306-d562-4271-aa74-c97040a76a45

https://github.com/user-attachments/assets/28b1c61a-2dde-4f31-a8d0-ab954a8fab02

**stage2_zeroscope_144x80.yaml**:
```yaml
name: "zeroscope_stage2_wo_scheduler_swap"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "../dream-in-4D-output"
seed: 0

data_type: "random-camera-trajectory-datamodule"
data:
  batch_size: [1]
  width: [144]
  height: [80]
  num_frames: [24]
  resolution_milestones: []
  camera_distance_range: [0.8, 1.0] # relative
  fovy_range: [15, 60]
  azimuth_range: [-150, 150]
  elevation_range: [0, 45]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  n_val_views: 48
  n_test_views: 192
  n_split_val: 4
  n_split_test: 8
  eval_height: 512
  eval_width: 512
  delta_percentage: 0.0
  delta_time: 0.2
  eval_elevation_deg: 15.0
  eval_camera_distance: 3.0
  eval_fovy_deg: 40.


system_type: "zeroscope-system"
system:
  geometry_convert_inherit_texture: True
  geometry_type: "deformable-implicit-volume"
  geometry:
    radius: 1.0
    normal_type: "analytic"
    output_displacement: True

    # use Magic3D density initialization instead
    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    optimize_geometry: False
    optimize_deformation: True

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

    time_encoding_config:
      otype: ProgressiveBandHashGrid
      type: 'Hash'
      n_levels: 12
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 4
      per_level_scale: 1.447269237440378 # max resolution 233
      start_level: 4
      start_step: 0
      update_steps: 500

    mlp_network_config:
      otype: "VanillaMLP"
      activation: "ReLU"
      output_activation: "none"
      n_neurons: 64
      n_hidden_layers: 1

    mlp_deformation_network_config:
      otype: "VanillaMLP"
      activation: "ReLU"
      output_activation: "none"
      n_neurons: 64
      n_hidden_layers: 4

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true
    share_aug_bg: true
    mlp_network_config:
      otype: "VanillaMLP"
      activation: "ReLU"
      n_neurons: 64
      n_hidden_layers: 3
    dir_encoding_config:
      otype: "SphericalHarmonics"
      degree: 3

  renderer_type: "deformable-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512
    return_comp_normal: False
    return_normal_perturb: False
    return_comp_displacement: True

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    pretrained_model_name_or_path: 'cerspense/zeroscope_v2_576w'
    prompt: ${system.prompt_processor.prompt}
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "zeroscope-guidance"
  guidance:
    img_size: [320, 576]
    half_precision_weights: True
    guidance_scale: 100.
    pretrained_model_name_or_path: 'cerspense/zeroscope_v2_576w'
    view_dependent_prompting: True
    min_step_percent: [0, 0.99, 0.2, 10000]
    max_step_percent: [0, 0.99, 0.5, 10000]
    use_hifa: True
    num_hifa_steps: 4
    guidance_cache_dir: '/root/.cache/huggingface/hub'

  freq:
    guidance_eval: 1000

  loggers:
    wandb:
      enable: False
      project: "threestudio"
      name: ${tag}

  loss:
    lambda_sds_video: 1.0
    lambda_sds_color: 0.1
    lambda_deformation_spatial_reg: 1000.

  optimizer:
    name: AdamW
    args:
      betas:
        - 0.9
        - 0.99
      eps: 1.0e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.deformation_encoding:
        lr: 0.001
      geometry.density_network:
        lr: 0.001
      geometry.feature_network:
        lr: 0.001
      geometry.deformation_network:
        lr: 0.001
      background:
        lr: 0.001
  scheduler:
    interval: "step"
    name: "MultiStepLR"
    args:
      gamma: 0.5
      milestones: [8000, 9000]

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 500
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: 500
```

**panda_bicycle.yaml**
```yaml
system:
  geometry:
    deformation_scale: 2.0
  prompt_processor:
    prompt: "A panda is riding a bicycle"
  geometry_convert_from: "../dream-in-4D-output/MVdream_SD/_A_panda_is_riding_a_bicycle@20240714-112543/ckpts/last.ckpt"
```
